FROM meacomplaintdockerhub/mea_app:prod AS app

FROM meacomplaintdockerhub/mea_php-fpm:prod

###########################################################################
# Copy directories
###########################################################################

WORKDIR /var/www

COPY --from=app /var/www .

RUN chown -R www-data:www-data \
        /var/www/storage \
        /var/www/bootstrap/cache

CMD ["php-fpm"]

EXPOSE 9000